services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot cinema -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cinema
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root

        JWT_SECRET: VerySecretKeyVerySecretKeyVerySecretKeyVerySecretKey
        JWT_EXPIRATION: 86400000