spring.application.name=CinemaReservationSystem

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=local

# Enables automatic creation of a default admin user on application startup
app.seed.add-admin=true

# Enables demo mode data seeding (populates the database with sample data for development or presentation purposes)
app.seed.demo-mode=true
